= How long does it take you to create a RevealJS presentation ?

:hp-tags: asciidoctor, revealjs, lazybones

After couple of months, I finally found a topic to create the very first topic in my new http://hubpress.io/[Hubpress.io] blog.

Today, we are going to talk about *Asciidoctor* and *RevealJS*. As you might know, you can use Asciidoctor to write and create RevealJS presentations. Therefore, if you are not familiar with Asciidoctor creating the first presentation can be tricky especially if you plan to use diagrams (or other external modules).

Recently thanks to Andres Almiray (https://twitter.com/aalmiray[@aalmiray]), I discovered https://github.com/pledbrook/lazybones[Lazybones]. A very simple template generator for Gradle projects. With Lazybones you can start a Gradle projects such as Spring boot, Groovy or even AsciidoctorJ using only 1 command. Therefore you still had to  customize the generated project to be able to generate a RevealJS slideshow.

That's why I have created the Asciidoctor-RevealJS template for Lazybones.

== Long story short

=== Let's play

Once you installed everything (GVM and Lazybones) all you need to do is:

[source]
lazybones create asciidoctor-revealjs 0.1 myAwesomePresentation

Then answer the questions (title for your presentation, who you are and the revealjs theme) and you are good to go.
icon:thumbs-o-up[]

If you look your current directory you will found something like:

[source]
----
gscheibel@~/labs/adocs/blog/myAwesomePresentation $ tree
├── README.md
├── build.gradle
└── src
    └── docs
        └── asciidoc
            ├── images
            ├── slides
            ├── slides.adoc
            ├── snippets
            └── styles
----

All you need is under `src/docs/asciidoc/`, by default the main slide is `slides.adoc`. Remember the questions asked during the presentation setup, those information (title and author) are reused here. The theme can be found in the `build.gradle` file.

[source]
----
= Asciidoctor is awesome
Guillaume Scheibel <guillaume.scheibel@gmail.com>

:imagesdir: images
:sourcedir: snippets
----

=== Let's write

A way to create your presentation is `one slide one file`, it means every time you want to create a slide, you create a file (in slides/ for instance) and then include it in slides.adoc using the include directive (eg: `include::slides/coolSlides.adoc[]`)
